First attempt editing the Image Segmentation section
ABI-Tutorials/DTP-Segmentation pull request #1
Opened 2018-09-06 04:43 UTC by shsa992

This is my first attempt to follow and edit the Image Segmentation section. From my understanding, we are required to add latest screenshots. Also, I was not very comfortable following the Task 4 section under this topic. I have made few edits. Kindly review and provide your valuable feedback.

2018-09-18 05:15 UTC, hsorby reviewed
Overall it looks good but we should add some Sphinx markup for anything that refers to GUI objects/widgets.  Like the view toolbox etc.

2018-09-18 05:15 UTC, hsorby commented on source/imagesegmentation.rst
> +From the *view* toolbox on the left-hand side we can show the image planes and from the *file* toolbox we can load and save our progress. The done button is also in the file toolbox for when we are f
The *view* toolbox could probably be better labelled with a :guilable: Sphinx markup rather than italics (and others).

2018-09-25 00:19 UTC, shsa992 commented
I have added required Sphinx markup in this Image Segmentation topic. All the old screenshots has been replaced by the new version of MAP client screenshots. Task 3 and the "Finish" section are incomplete so requires inputs from the concerned person to get it done. Kindly review.

2018-09-25 22:08 UTC, hsorby requested changes
We are using version control so we don't need to keep old files.  Please delete all images that are marked -OLD.

2018-09-25 22:18 UTC, shsa992 commented
Needful has been done. I had kept those OLD snips in case the new screenshots were not as desired.

2019-02-28 03:22 UTC, merged